### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by pld** [onaio/karma#13]
* [X] Use JS translation library
* [X] Move current text to a translation file
* [X] Move translation text to Transifex

---

### Implementation plan

- [X] Update the conversation to Karma v0.8
