### ISSUE TITLE
Make Karma conversation only

### ISSUE THREAD

**Issue by urbanslug** [onaio/karma#18]
Update this repo to only hold the conversation and extract a library out of it for reusability of code.

### Implementation plan
- [ ] Update the README
- [ ] Extract a library out of this repo.
Structure:
```
```

- [ ] Leave this to hold code that is specific to the conversation.
Structure:
```
~/code/karma » tree -I 'node_modules|*~'
.
├── Dockerfile
├── LICENSE
├── README.md
├── docker-compose.yml
├── ecosystem.config.js
├── karma.js
├── media
│   └── sharing
│       ├── messenger_code_1504460956262236\ (1).png
│       ├── messenger_code_1504460956262236\ (2).png
│       └── messenger_code_1504460956262236.png
├── package.json
└── translations
    ├── en.json
    ├── in.json
    └── pt.json
```

### Blocking or related issues
 - [ ] Create a repo to hold the library
 - [ ] Publish that library to npm (a pre-release)
 - [ ] Depend on that library
 - [ ] Make sure it still works with the current deploy env, that is, docker.
